project:
  type: website

website:
  title: "Twinko AI :: Info Hub"
  navbar:
    logo: "image/logo-black.png"
    left:
      - href: index.qmd
        text: Home
      - href: news/index.qmd
        text: News

    tools:
      - icon: twitter
        href: https://twitter.com/tengfei
        text: Twitter
      - icon: github
        href: https://github.com/twinko-ai
        text: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



